In [1]:
!pip install pandas==1.1.0

Requirement already satisfied: pandas==1.1.0 in /usr/local/lib/python3.7/dist-packages (1.1.0)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas==1.1.0) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas==1.1.0) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas==1.1.0) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas==1.1.0) (1.15.0)

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [3]:
%cd '/content/drive/My Drive/Datasets/Cursos'
!ls

/content/drive/My Drive/Datasets/Cursos
london_bikes.csv  Meteorite_Landings.csv  Poblacion.csv

In [4]:
import pandas as pd
import numpy as np

In [5]:
pob = pd.read_csv('Poblacion.csv')
pob

                    Country Name Country Code  ...         2019         2020
0                          Aruba          ABW  ...     106310.0     106766.0
1    Africa Eastern and Southern          AFE  ...  660046272.0  677243299.0
2                    Afghanistan          AFG  ...   38041757.0   38928341.0
3     Africa Western and Central          AFW  ...  446911598.0  458803476.0
4                         Angola          AGO  ...   31825299.0   32866268.0
..                           ...          ...  ...          ...          ...
261                       Kosovo          XKX  ...    1788878.0    1775378.0
262                  Yemen, Rep.          YEM  ...   29161922.0   29825968.0
263                 South Africa          ZAF  ...   58558267.0   59308690.0
264                       Zambia          ZMB  ...   17861034.0   18383956.0
265                     Zimbabwe          ZWE  ...   14645473.0   14862927.0

[266 rows x 65 columns]

In [10]:
pob = pob.drop(columns=['Country Code','Indicator Name','Indicator Code','2019'])

pob = pd.melt(pob, id_vars=["Country Name"],
var_name="year", value_name="pob")

pob

                      Country Name  year          pob
0                            Aruba  1960      54208.0
1      Africa Eastern and Southern  1960  130836765.0
2                      Afghanistan  1960    8996967.0
3       Africa Western and Central  1960   96396419.0
4                           Angola  1960    5454938.0
...                            ...   ...          ...
15955                       Kosovo  2020    1775378.0
15956                  Yemen, Rep.  2020   29825968.0
15957                 South Africa  2020   59308690.0
15958                       Zambia  2020   18383956.0
15959                     Zimbabwe  2020   14862927.0

[15960 rows x 3 columns]

In [12]:
#formato legible para la poblacion
pd.options.display.float_format = '{:,.1f}'.format
pob

                      Country Name  year           pob
0                            Aruba  1960      54,208.0
1      Africa Eastern and Southern  1960 130,836,765.0
2                      Afghanistan  1960   8,996,967.0
3       Africa Western and Central  1960  96,396,419.0
4                           Angola  1960   5,454,938.0
...                            ...   ...           ...
15955                       Kosovo  2020   1,775,378.0
15956                  Yemen, Rep.  2020  29,825,968.0
15957                 South Africa  2020  59,308,690.0
15958                       Zambia  2020  18,383,956.0
15959                     Zimbabwe  2020  14,862,927.0

[15960 rows x 3 columns]

In [18]:
#año converida a variable categorica para el manejo de multiples indices
pob['year'] = pd.Categorical(pob['year'].apply(str))
pob.dtypes

Country Name      object
year            category
pob              float64
dtype: object

In [19]:
#filtro para seleccion de paises
#isin == crea vector de variables booleanas
idxFiltro = pob['Country Name'].isin(['Aruba', 'Colombia'])
idxFiltro

0         True
1        False
2        False
3        False
4        False
         ...
15955    False
15956    False
15957    False
15958    False
15959    False
Name: Country Name, Length: 15960, dtype: bool

In [25]:
pobEjemplo = pob[idxFiltro]
pobEjemplo

      Country Name  year          pob
0            Aruba  1960     54,208.0
45        Colombia  1960 16,057,714.0
266          Aruba  1961     55,434.0
311       Colombia  1961 16,567,817.0
532          Aruba  1962     56,234.0
...            ...   ...          ...
15207     Colombia  2017 48,909,844.0
15428        Aruba  2018    105,846.0
15473     Colombia  2018 49,661,056.0
15694        Aruba  2020    106,766.0
15739     Colombia  2020 50,882,884.0

[120 rows x 3 columns]

In [26]:
#nombre y año se convierten en indices
pobEjemplo = pobEjemplo.set_index(['Country Name', 'year']).sort_index()
pobEjemplo

                           pob
Country Name year
Aruba        1960     54,208.0
             1961     55,434.0
             1962     56,234.0
             1963     56,699.0
             1964     57,029.0
...                        ...
Colombia     2015 47,520,667.0
             2016 48,175,048.0
             2017 48,909,844.0
             2018 49,661,056.0
             2020 50,882,884.0

[120 rows x 1 columns]

In [28]:
# seleccionar colombia
pobEjemplo.loc['Colombia', :]

              pob
year
1960 16,057,714.0
1961 16,567,817.0
1962 17,092,919.0
1963 17,629,978.0
1964 18,175,187.0
1965 18,725,242.0
1966 19,279,734.0
1967 19,837,508.0
1968 20,393,704.0
1969 20,942,453.0
1970 21,480,064.0
1971 22,003,983.0
1972 22,516,429.0
1973 23,024,512.0
1974 23,538,390.0
1975 24,065,502.0
1976 24,608,102.0
1977 25,164,544.0
1978 25,733,669.0
1979 26,312,996.0
1980 26,900,508.0
1981 27,496,608.0
1982 28,101,824.0
1983 28,714,183.0
1984 29,331,230.0
1985 29,951,194.0
1986 30,572,479.0
1987 31,195,417.0
1988 31,822,527.0
1989 32,457,497.0
1990 33,102,569.0
1991 33,758,328.0
1992 34,422,568.0
1993 35,091,272.0
1994 35,758,978.0
1995 36,421,438.0
1996 37,076,387.0
1997 37,723,803.0
1998 38,364,307.0
1999 38,999,468.0
2000 39,629,965.0
2001 40,255,956.0
2002 40,875,363.0
2003 41,483,872.0
2004 42,075,953.0
2005 42,647,731.0
2006 43,200,901.0
2007 43,737,512.0
2008 44,254,972.0
2009 44,750,054.0
2010 45,222,699.0
2011 45,662,747.0
2012 46,075,721.0
2013 46,495,492.0
2014 46,967,706.0
2015 47,520,667.0
2016 48,175,048.0
2017 48,909,844.0
2018 49,661,056.0
2020 50,882,884.0

In [29]:
# seleccionar colombia y un año en particular
pobEjemplo.loc['Colombia', :].loc['2016',:]

pob   48,175,048.0
Name: 2016, dtype: float64

In [30]:
#anidar busqueda
pobEjemplo.xs(['Aruba'])

           pob
year
1960  54,208.0
1961  55,434.0
1962  56,234.0
1963  56,699.0
1964  57,029.0
1965  57,357.0
1966  57,702.0
1967  58,044.0
1968  58,377.0
1969  58,734.0
1970  59,070.0
1971  59,442.0
1972  59,849.0
1973  60,236.0
1974  60,527.0
1975  60,653.0
1976  60,586.0
1977  60,366.0
1978  60,102.0
1979  59,972.0
1980  60,097.0
1981  60,561.0
1982  61,341.0
1983  62,213.0
1984  62,826.0
1985  63,024.0
1986  62,645.0
1987  61,838.0
1988  61,072.0
1989  61,033.0
1990  62,152.0
1991  64,623.0
1992  68,240.0
1993  72,495.0
1994  76,705.0
1995  80,324.0
1996  83,211.0
1997  85,450.0
1998  87,280.0
1999  89,009.0
2000  90,866.0
2001  92,892.0
2002  94,992.0
2003  97,016.0
2004  98,744.0
2005 100,028.0
2006 100,830.0
2007 101,226.0
2008 101,362.0
2009 101,452.0
2010 101,665.0
2011 102,050.0
2012 102,565.0
2013 103,165.0
2014 103,776.0
2015 104,339.0
2016 104,865.0
2017 105,361.0
2018 105,846.0
2020 106,766.0

In [31]:
#busqueda de multiples indices
pobEjemplo.xs(['Aruba', '2018'])

pob   105,846.0
Name: (Aruba, 2018), dtype: float64

In [33]:
#seleccion a bajo nivel
pobEjemplo.xs('2018', level='year')

                      pob
Country Name
Aruba           105,846.0
Colombia     49,661,056.0

In [34]:
#ordenados A-Z por indices
paises = pob.set_index(['Country Name', 'year']).sort_index()
paises

                           pob
Country Name year
Afghanistan  1960  8,996,967.0
             1961  9,169,406.0
             1962  9,351,442.0
             1963  9,543,200.0
             1964  9,744,772.0
...                        ...
Zimbabwe     2015 13,814,642.0
             2016 14,030,338.0
             2017 14,236,599.0
             2018 14,438,812.0
             2020 14,862,927.0

[15960 rows x 1 columns]

In [35]:
#ordenado Z-A por indices
paises = pob.set_index(['Country Name', 'year']).sort_index(ascending= [False, True])
paises

                           pob
Country Name year
Zimbabwe     1960  3,776,679.0
             1961  3,905,038.0
             1962  4,039,209.0
             1963  4,178,726.0
             1964  4,322,854.0
...                        ...
Afghanistan  2015 34,413,603.0
             2016 35,383,028.0
             2017 36,296,111.0
             2018 37,171,922.0
             2020 38,928,341.0

[15960 rows x 1 columns]

In [37]:
#obtener multiples elementos del df
#elementos entre Aruba y Austria y que vayan del 2015 al 2017
ids = pd.IndexSlice
paises.loc[ids['Aruba': 'Austria', '2015':'2017'],:].sort_index()

UnsortedIndexError: ignored

In [39]:
#primeros indices (nombre)
paises.index.get_level_values(0)

Index(['Zimbabwe', 'Zimbabwe', 'Zimbabwe', 'Zimbabwe', 'Zimbabwe', 'Zimbabwe',
       'Zimbabwe', 'Zimbabwe', 'Zimbabwe', 'Zimbabwe',
       ...
       'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan',
       'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan',
       'Afghanistan', 'Afghanistan'],
      dtype='object', name='Country Name', length=15960)

In [38]:
#segundos indices (años)
paises.index.get_level_values(1)

CategoricalIndex(['1960', '1961', '1962', '1963', '1964', '1965', '1966',
                  '1967', '1968', '1969',
                  ...
                  '2010', '2011', '2012', '2013', '2014', '2015', '2016',
                  '2017', '2018', '2020'],
                 categories=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', ...], ordered=False, name='year', dtype='category', length=15960)

In [43]:
paises['pob']['Colombia']['2018']

49661056.0

In [45]:
#suma de la poblacion mundial por año
paises.sum(level='year')

                  pob
year
1960 30,970,254,364.0
1961 31,378,681,037.0
1962 31,935,522,829.0
1963 32,627,288,430.0
1964 33,324,651,954.0
1965 34,039,268,447.0
1966 34,791,710,688.0
1967 35,542,559,151.0
1968 36,311,509,931.0
1969 37,107,924,065.0
1970 37,921,633,179.0
1971 38,761,975,862.0
1972 39,586,926,987.0
1973 40,410,577,291.0
1974 41,229,610,923.0
1975 42,034,983,471.0
1976 42,832,349,051.0
1977 43,624,966,813.0
1978 44,431,379,219.0
1979 45,257,297,174.0
1980 46,093,525,025.0
1981 46,952,359,966.0
1982 47,846,606,647.0
1983 48,751,597,446.0
1984 49,656,312,935.0
1985 50,578,915,497.0
1986 51,528,604,325.0
1987 52,503,949,861.0
1988 53,490,209,468.0
1989 54,475,587,143.0
1990 55,473,925,126.0
1991 56,449,522,188.0
1992 57,397,630,027.0
1993 58,348,613,075.0
1994 59,290,066,556.0
1995 60,230,214,779.0
1996 61,158,476,736.0
1997 62,085,133,917.0
1998 63,003,035,467.0
1999 63,909,432,535.0
2000 64,809,786,732.0
2001 65,706,025,855.0
2002 66,601,653,971.0
2003 67,502,063,312.0
2004 68,408,684,980.0
2005 69,322,139,550.0
2006 70,242,767,162.0
2007 71,168,977,697.0
2008 72,109,715,796.0
2009 73,054,980,365.0
2010 74,003,782,523.0
2011 74,959,600,104.0
2012 75,950,255,197.0
2013 76,955,905,190.0
2014 77,964,946,538.0
2015 78,971,902,017.0
2016 79,982,705,474.0
2017 80,996,992,699.0
2018 81,990,164,659.0
2020 83,910,632,389.0

In [47]:
#cambiar formato de indices
#convertir indices en columnas
pobEjemplo.unstack('Country Name')

                   pob
Country Name     Aruba     Colombia
year
1960          54,208.0 16,057,714.0
1961          55,434.0 16,567,817.0
1962          56,234.0 17,092,919.0
1963          56,699.0 17,629,978.0
1964          57,029.0 18,175,187.0
1965          57,357.0 18,725,242.0
1966          57,702.0 19,279,734.0
1967          58,044.0 19,837,508.0
1968          58,377.0 20,393,704.0
1969          58,734.0 20,942,453.0
1970          59,070.0 21,480,064.0
1971          59,442.0 22,003,983.0
1972          59,849.0 22,516,429.0
1973          60,236.0 23,024,512.0
1974          60,527.0 23,538,390.0
1975          60,653.0 24,065,502.0
1976          60,586.0 24,608,102.0
1977          60,366.0 25,164,544.0
1978          60,102.0 25,733,669.0
1979          59,972.0 26,312,996.0
1980          60,097.0 26,900,508.0
1981          60,561.0 27,496,608.0
1982          61,341.0 28,101,824.0
1983          62,213.0 28,714,183.0
1984          62,826.0 29,331,230.0
1985          63,024.0 29,951,194.0
1986          62,645.0 30,572,479.0
1987          61,838.0 31,195,417.0
1988          61,072.0 31,822,527.0
1989          61,033.0 32,457,497.0
1990          62,152.0 33,102,569.0
1991          64,623.0 33,758,328.0
1992          68,240.0 34,422,568.0
1993          72,495.0 35,091,272.0
1994          76,705.0 35,758,978.0
1995          80,324.0 36,421,438.0
1996          83,211.0 37,076,387.0
1997          85,450.0 37,723,803.0
1998          87,280.0 38,364,307.0
1999          89,009.0 38,999,468.0
2000          90,866.0 39,629,965.0
2001          92,892.0 40,255,956.0
2002          94,992.0 40,875,363.0
2003          97,016.0 41,483,872.0
2004          98,744.0 42,075,953.0
2005         100,028.0 42,647,731.0
2006         100,830.0 43,200,901.0
2007         101,226.0 43,737,512.0
2008         101,362.0 44,254,972.0
2009         101,452.0 44,750,054.0
2010         101,665.0 45,222,699.0
2011         102,050.0 45,662,747.0
2012         102,565.0 46,075,721.0
2013         103,165.0 46,495,492.0
2014         103,776.0 46,967,706.0
2015         104,339.0 47,520,667.0
2016         104,865.0 48,175,048.0
2017         105,361.0 48,909,844.0
2018         105,846.0 49,661,056.0
2020         106,766.0 50,882,884.0

In [49]:
pobEjemplo.unstack('year')

                      pob               ...
year                 1960         1961  ...         2018         2020
Country Name                            ...
Aruba            54,208.0     55,434.0  ...    105,846.0    106,766.0
Colombia     16,057,714.0 16,567,817.0  ... 49,661,056.0 50,882,884.0

[2 rows x 60 columns]